name: Run Python Script Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Every hour (UTC time)
  workflow_dispatch:      # Allow manual run

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # Disables default token to use PAT

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python trial.py  # Replace with the name of your Python script

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Updates
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Use your Personal Access Token (PAT)
        run: |
          git add prediction/*          # Add updated output files
          git commit -m "Update predictions (auto-run)"
          git push https://${{ secrets.GH_PAT }}@github.com/<username>/<repo>.git HEAD:main
